---

- name: Deprecation warning
  when: deprecation_msg is defined
  run_once: true
  cloudera.cluster.warn:
    msg: "{{ deprecation_msg }}"

- name: Set session timeout to 30 days
  cloudera.cluster.cm_api:
    endpoint: /cm/config
    method: PUT
    body: "{{ lookup('template', 'unlog.json') }}"
  notify:
    - restart cloudera-scm-server
