---

- name: Deprecation warning
  run_once: true
  cloudera.cluster.deprecation:
    msg: "Role, {{ ansible_role_name }}, is no longer supported."
    version: 6.0.0

- name: Set session timeout to 30 days
  cloudera.cluster.cm_api:
    endpoint: /cm/config
    method: PUT
    body: "{{ lookup('template', 'unlog.json') }}"
  notify:
    - restart cloudera-scm-server
