# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Install acls package
  ansible.builtin.package:
    lock_timeout: 60
    name: acl
    state: present

- name: Change permissions on keystore
  file:
    state: file
    path: "{{ tls_keystore_path }}"
    mode: 0640
    owner: root
    group: hadoop

- name: Add ACLs to keystore
  acl:
    path: "{{ tls_keystore_path }}"
    entity: "{{ account.user }}"
    etype: group
    permissions: r
    state: present
  loop: "{{ local_accounts | json_query('[?@.keystore_acl]') }}"
  loop_control:
    loop_var: account
    label: "{{ account.user }}"
  when: account.when | default(True)

- name: Change permissions on private key
  file:
    state: file
    path: "{{ tls_key_path }}"
    mode: 0440
    owner: root
    group: root

- name: Add ACLs to private key
  acl:
    path: "{{ tls_key_path }}"
    entity: "{{ account.user }}"
    etype: group
    permissions: r
    state: present
  loop: "{{ local_accounts | json_query('[?@.key_acl]') }}"
  loop_control:
    loop_var: account
    label: "{{ account.user }}"
  when: account.when | default(True)

- name: Change permissions on key password file
  file:
    state: file
    path: "{{ tls_key_password_file }}"
    mode: 0440
    owner: root
    group: root

- name: Add ACLs to key password file
  acl:
    path: "{{ tls_key_password_file }}"
    entity: "{{ account.user }}"
    etype: user
    permissions: r
    state: present
  loop: "{{ local_accounts | json_query('[?@.key_password_acl]') }}"
  loop_control:
    loop_var: account
    label: "{{ account.user }}"
  when: account.when | default(True)

- name: Change permissions on unencrypted key
  file:
    state: file
    path: "{{ tls_key_path_plaintext }}"
    mode: 0440
    owner: root
    group: root

- name: Add ACLs to unencrypted key
  acl:
    path: "{{ tls_key_path_plaintext }}"
    entity: "{{ account.user }}"
    etype: group
    permissions: r
    state: present
  loop: "{{ local_accounts | json_query('[?@.unencrypted_key_acl]') }}"
  loop_control:
    loop_var: account
    label: "{{ account.user }}"
  when: account.when | default(True)
