---

- name: Load defaults
  when: deprecation_msg is defined
  run_once: true
  ansible.builtin.include_role:
    name: cloudera.cluster.cloudera_manager.common

- name: Deprecation warning
  when: deprecation_msg is defined
  run_once: true
  cloudera.cluster.warn:
    msg: "{{ deprecation_msg }}"

- assert:
    that:
      - altus_private_key | length > 0
      - altus_key_id | length > 0
    quiet: true
    fail_msg: >-
      Altus key id and private key must be provided to configure Telemetry service for WXM

- name: Configure Telemetry
  ansible.builtin.include_tasks: configure_telemetry.yml

- name: Configure Truststore in Agent for base
  ansible.builtin.include_tasks: truststore_to_base.yml

- name: Restart Telemetry Publisher
  include_role:
    name: cloudera.cluster.operations.restart_mgmt_services
  vars:
    services_to_restart:
      - mgmt-TELEMETRYPUBLISHER

- name: Restart Base Cluster Services
  include_role:
    name: cloudera.cluster.operations.restart_cluster_services
  vars:
    services_to_restart:
      - HIVE
      - HIVE_ON_TEZ
      - SPARK_ON_YARN
      - IMPALA
      - WXM
