# Copyright 2023 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

namespace: cloudera
name: cluster
version: 3.4.1

authors: []
readme: README.md
description: Cloudera assets for managing Cloudera clusters
license_file: 'LICENSE'
tags: []

dependencies:
  'ansible.posix': '1.3.0'
  'community.crypto': '2.2.1'
  'community.general': '4.5.0'
  'community.mysql': '3.1.0'
  'community.postgresql': '1.6.1'
  'freeipa.ansible_freeipa': '1.6.2'

repository: https://github.com/cloudera-labs/cloudera.cluster
documentation: https://github.com/cloudera-labs/cloudera.cluster
homepage: https://github.com/cloudera-labs/cloudera.cluster
issues: https://github.com/cloudera-labs/cloudera.cluster/issues
