---

- name: Load defaults
  when: deprecation_msg is defined
  run_once: true
  ansible.builtin.include_role:
    name: cloudera.cluster.cloudera_manager.common

- name: Deprecation warning
  when: deprecation_msg is defined
  run_once: true
  cloudera.cluster.warn:
    msg: "{{ deprecation_msg }}"

- name: Restart cluster
  cm_api:
    endpoint: /clusters/{{ cluster_to_restart }}/commands/restart
    method: POST
    timeout: "{{ cluster_restart_timeout | default(3000) }}"

- name: Re-deploy client configurations
  cm_api:
    endpoint: /clusters/{{ cluster_to_restart }}/commands/deployClientConfig
    method: POST
    timeout: "{{ cluster_restart_timeout | default(3000) }}"
