# Copyright 2024 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Prepare
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Set up Cloudera Manager package repository
      ansible.builtin.import_role:
        name: cm_repo

    - name: Set up Python
      ansible.builtin.import_role:
        name: prereq_python

    - name: Set up Java
      ansible.builtin.import_role:
        name: prereq_jdk

    - name: Set up PostgreSQL server
      ansible.builtin.import_role:
        name: postgresql_server

    - name: Set up PostgreSQL client
      ansible.builtin.import_role:
        name: postgresql_client

    - name: Set up Cloudera Manager database user
      community.general.postgresql_user:
        name: scm
        password: testpassword
      become_user: postgres

    - name: Set up Cloudera Manager database
      community.general.postgresql_db:
        name: scm
        owner: scm
        encoding: UTF-8
      become_user: postgres
