---

- name: Load defaults
  when: deprecation_msg is defined
  run_once: true
  ansible.builtin.include_role:
    name: cloudera.cluster.cloudera_manager.common

- name: Deprecation warning
  when: deprecation_msg is defined
  run_once: true
  cloudera.cluster.warn:
    msg: "{{ deprecation_msg }}"

- name: Create in Ranger the SolR service
  register: __ranger_solr_plugin
  uri:
    url: "{{ ranger_url }}/service/public/v2/api/service"
    method: POST
    user: "{{ ranger_user }}"
    password: "{{ ranger_password }}"
    return_content: true
    body: "{{ lookup('template', 'solr_plugin.json' ) }}"
    body_format: json
    status_code: 200
    validate_certs: false
    force_basic_auth: true
  no_log: true
  failed_when:
    - __ranger_solr_plugin is failed
    - "'Duplicate service name' not in __ranger_solr_plugin.json.msgDesc"

# Restart SolR

- name: Restart SolR
  cloudera.cluster.cm_api:
    endpoint: "/clusters/{{ cluster_name | urlencode() }}/services/{{ solr_service_name | lower }}/commands/restart"
  when: __ranger_solr_plugin.changed
