---

- name: Load defaults
  when: deprecation_msg is defined
  run_once: true
  ansible.builtin.include_role:
    name: cloudera.cluster.cloudera_manager.common

- name: Deprecation warning
  when: deprecation_msg is defined
  run_once: true
  cloudera.cluster.warn:
    msg: "{{ deprecation_msg }}"

- name: Restart Cloudera Manager Management Services
  cloudera.cluster.cm_api:
    endpoint: "/cm/service/roleCommands/restart"
    method: POST
    body:
      items: "{{ services_to_restart }}"
