---

- name: Deprecation warning
  run_once: true
  cloudera.cluster.deprecation:
    msg: "Role, {{ ansible_role_name }}, is no longer supported."
    version: 6.0.0

- name: Restart Cloudera Manager Management Services
  cloudera.cluster.cm_api:
    endpoint: "/cm/service/roleCommands/restart"
    method: POST
    body:
      items: "{{ services_to_restart }}"
