# Copyright 2024 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

argument_specs:
  main:
    short_description: "Download CSDs"
    description:
      - Downloads a specified list of Cloudera Custom Services Descriptor (CSD) files.
    author:
      - "Jim Enright <jenright@cloudera.com>"
    version_added: 5.0.0
    options:
      cloudera_manager_csd_directory:
        description: Location where CSDs are downloaded
        type: str
        required: false
        default: "/opt/cloudera/csd"
      cloudera_manager_csds:
        description: List of CSD jars URLs to download
        type: list
        elements: str
        required: false
        default: []
      cloudera_manager_csd_restarted:
        description: Flag to restart Cloudera Manager Server if CSDs are downloaded.
        type: bool
        required: false
        default: false
      cloudera_manager_repo_username:
        description:
          - Cloudera package repository username
      cloudera_manager_repo_password:
        description:
          - Cloudera package repository password
