---

name: Validate Pull Request documentation

on:
  pull_request:
    branches:
      - 'release/**'
      - 'devel'
    
  workflow_dispatch:

jobs:
  validate-docs:
    name: Validate Ansible Docs
    uses: cloudera-labs/github-actions/.github/workflows/lint-ansible-docs.yml@v1
    with:
      antsibull-log-upload: true
      collection-namespace: cloudera
      collection-name: cluster